# Generated by Django 4.1.3 on 2022-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_employer',
            field=models.BooleanField(verbose_name='Работодатель:'),
        ),
    ]
