# Generated by Django 4.1.3 on 2022-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experiences',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.CharField(choices=[('ВЫБРАТЬ', 'Выбрать'), ('IT', 'IT'), ('ФИНАНСЫ', 'Финансы'), ('МАРКЕТИНГ', 'Маркетинг'), ('ЮРИСТ', 'Юрист'), ('ИНЖЕНЕР', 'Инженер')], default='ВЫБРАТЬ', max_length=200, verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='job',
            name='experiences',
            field=models.CharField(default='Нет опыта', max_length=200, verbose_name='Experiences'),
        ),
    ]
