# Generated by Django 4.1.3 on 2022-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
        ('employer', '0002_remove_job_categories_remove_job_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.categoryjob', verbose_name='Катeгория вакансии'),
        ),
    ]
