# Generated by Django 4.1.3 on 2022-11-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_alter_job_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Детальное описание вакансии включающее в себя требования по знаниям соискателя'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experiences',
            field=models.CharField(default='Нет опыта', max_length=200, verbose_name='Требуемый опыт от и до (лет)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
