# Generated by Django 4.1.3 on 2022-11-25 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название(должность)')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Ожидаемая заработная плата')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.categoryjob', verbose_name='Катeгория вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=50, verbose_name='Организация')),
                ('responsibility', models.TextField(max_length=2000, verbose_name='Обязанности')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='applicant.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название учебного заведения')),
                ('faculty', models.CharField(max_length=50, verbose_name='Факультет')),
                ('speciality', models.CharField(max_length=50, verbose_name='Специальность')),
                ('end_date_education', models.DateField(verbose_name='Дата окончания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='applicant.resume', verbose_name='Резюме')),
            ],
        ),
    ]
